### ISSUE TITLE
.gitmodules为何要是git@github.com这种ssh的格式？

### ISSUE THREAD

**Issue by rexdf** [TkYu/ChromeUpdater#1]
`url = git@github.com:facebook-csharp-sdk/simple-json.git`

这句话的意思应该是：使用ssh协议，从github.com主机上以git用户名登录，获取facebook-csharp-sdk/simple-json.git文件夹。

而非授权用户根本没法访问的。

也就是必须要有facebook-csharp-sdk用户的私钥的才可能`git submodule update`成功。

而手动clone比较麻烦，如果修改.gitmodules文件，则会有merge conflict风险。

**Comment by TkYu** [comment]
![cap](https://cloud.githubusercontent.com/assets/2945229/19335278/f5e8836e-90b6-11e6-982f-0eb4d3eb3d9d.jpg)
我倒是没遇到过无法访问……

**Comment by rexdf** [comment]
https://github.com/rime/weasel/issues/67

https://github.com/rime/weasel/issues/68

**Comment by rexdf** [comment]
这个需要配置密钥，必须有github注册账户才能pull。

**Comment by TkYu** [comment]
我目前是由于工作原因不方便用https协议来使用git，如果你那边刚好不能用的话建议可以fork一份然后把gitmodules里的url改为https的

**Comment by rexdf** [comment]
如果要配置自动编译bot的话，一般来说ssh会比较不方便。作为开源出来的项目，而不是私有项目一般https是首选，云加速上应该也有优势。 

https://help.github.com/articles/which-remote-url-should-i-use/   github官方也是推荐https的。

不过就这个项目而言，当然也无所谓啦！

PS：本地有常年累积下来的300多个github的repo，每天一开机就会自动全部pull一遍。然而就只有这个开源项目的submodule用ssh协议，每次都是初始化失败的。

**Comment by rexdf** [comment]
看一下这个项目 https://github.com/Valloric/ycmd/blob/master/.gitmodules

以及这个 https://github.com/electron/electron/blob/master/.gitmodules

对于github上面的大型开源项目的submodule引用github项目的都是https的。
