### ISSUE TITLE
打开主程序会出现以下提示，麻烦作者看一下，谢谢！

### ISSUE THREAD

**Issue by Cyugin** [TkYu/ChromeUpdater#2]
![bug1](https://user-images.githubusercontent.com/26215118/28102291-dcdc1fd6-6700-11e7-95aa-9042d0d1d5be.PNG)
![bug2](https://user-images.githubusercontent.com/26215118/28102301-ece7f6e8-6700-11e7-9b46-81c26c220502.PNG)

**Comment by TkYu** [comment]
这个级别的错误可能是你的.net运行库出问题了，首先确定是否安装有.net 4.5及以上的运行库，如果有的话，尝试使用 https://www.microsoft.com/en-US/download/details.aspx?id=30135 这个工具来修复一下看看。（BTW：图中的这个是带有GreenChrome更新功能的闭源版本，相关的问题可以前往 https://bbs.shuax.com/ 交流，GitHub这里就只交流这个仓库的代码就好~）

**Comment by Cyugin** [comment]
好的，不好意思！谢谢解答！
